In [12]:
import numpy as np

# Define matrix A
# A = np.array([[1, 2, 3],
#               [4, 5, 6],
#               [7, 8, 9],
#               [10, 11, 12],
#               [13, 14, 15]])
#  make A as a random matrix of dimentsion 20x3 with values betweeen 0 to 9
A = np.random.randint(0, 10, (50, 2))

# Calculate A^T
A_transpose = np.transpose(A)

# Calculate A^TA
A_TA = np.dot(A_transpose, A)

# Print matrix A
print("Matrix A:")
for row in A:
    print(" ".join(str(elem).rjust(4) for elem in row))

# Print matrix A^T
print("\nTranspose of A (A^T):")
for row in A_transpose:
    print(" ".join(str(elem).rjust(4) for elem in row))

# Print the result A^TA
print("\nResult of A^T * A (A^TA):")
for row in A_TA:
    print(" ".join(str(elem).rjust(6) for elem in row))

# Output
AA_T= np.dot(A, A_transpose)
print("\nResult of A * A^T (AA^T):")
for row in AA_T:
    print(" ".join(str(elem).rjust(6) for elem in row))



Matrix A:
   3    4
   0    1
   7    8
   2    3
   7    9
   6    1
   8    7
   0    5
   3    3
   3    9
   6    5
   4    0
   7    0
   0    5
   0    0
   6    4
   1    7
   6    3
   5    4
   9    9
   1    1
   5    3
   3    3
   6    3
   3    3
   1    8
   3    3
   5    2
   4    2
   5    3
   8    9
   9    6
   7    9
   8    5
   3    5
   1    6
   2    6
   9    9
   2    3
   2    4
   8    6
   4    4
   1    3
   2    3
   3    9
   3    8
   9    9
   6    3
   2    6
   8    4

Transpose of A (A^T):
   3    0    7    2    7    6    8    0    3    3    6    4    7    0    0    6    1    6    5    9    1    5    3    6    3    1    3    5    4    5    8    9    7    8    3    1    2    9    2    2    8    4    1    2    3    3    9    6    2    8
   4    1    8    3    9    1    7    5    3    9    5    0    0    5    0    4    7    3    4    9    1    3    3    3    3    8    3    2    2    3    9    6    9    5    5    6    6    9    3    4    6    4    3   

In [13]:
print(A)
x = np.array([2, 3])
Ax = np.dot(A, x)
print("\nVector x:", x)

print("\nResult of A * x:")

print(Ax)
#  print Ax norm squared
print("\nNorm squared of A * x:", np.linalg.norm(Ax)**2)

[[3 4]
 [0 1]
 [7 8]
 [2 3]
 [7 9]
 [6 1]
 [8 7]
 [0 5]
 [3 3]
 [3 9]
 [6 5]
 [4 0]
 [7 0]
 [0 5]
 [0 0]
 [6 4]
 [1 7]
 [6 3]
 [5 4]
 [9 9]
 [1 1]
 [5 3]
 [3 3]
 [6 3]
 [3 3]
 [1 8]
 [3 3]
 [5 2]
 [4 2]
 [5 3]
 [8 9]
 [9 6]
 [7 9]
 [8 5]
 [3 5]
 [1 6]
 [2 6]
 [9 9]
 [2 3]
 [2 4]
 [8 6]
 [4 4]
 [1 3]
 [2 3]
 [3 9]
 [3 8]
 [9 9]
 [6 3]
 [2 6]
 [8 4]]

Vector x: [2 3]

Result of A * x:
[18  3 38 13 41 15 37 15 15 33 27  8 14 15  0 24 23 21 22 45  5 19 15 21
 15 26 15 16 14 19 43 36 41 31 21 20 22 45 13 16 34 20 11 13 33 30 45 21
 22 28]

Norm squared of A * x: 32151.0


In [14]:
# append b as a column to A
# b= np.array([5,2,5,7,9])
b= np.random.randint(0, 10, (len(A), 1))
Ab = np.column_stack((A,b))
print("\nMatrix Ab:")
for row in Ab:
    print(" ".join(str(elem).rjust(4) for elem in row))
# also add identity matrix to A of size 3x3 and 0s in the last column to A
I = np.identity(A.shape[1])
lmdSq=3
#  multiply each ellement of I by lambda
I=I*lmdSq
print("\nMatrix I:")
for row in I:
    print(" ".join(str(elem).rjust(4) for elem in row))
# I1=np.column_stack((I,np.zeros(3)))
I1=np.column_stack((I,np.zeros(A.shape[1])))
A_I = np.row_stack((Ab,I1))
print("\nMatrix A_I:")
# convert A_I to integer
A_I = A_I.astype(int)

for row in A_I:
    print(" ".join(str(elem).rjust(4) for elem in row))

A=A_I


Matrix Ab:
   3    4    8
   0    1    4
   7    8    1
   2    3    5
   7    9    6
   6    1    5
   8    7    0
   0    5    4
   3    3    8
   3    9    4
   6    5    5
   4    0    4
   7    0    1
   0    5    2
   0    0    9
   6    4    0
   1    7    6
   6    3    0
   5    4    9
   9    9    6
   1    1    1
   5    3    3
   3    3    3
   6    3    4
   3    3    5
   1    8    9
   3    3    7
   5    2    9
   4    2    3
   5    3    1
   8    9    2
   9    6    6
   7    9    6
   8    5    9
   3    5    0
   1    6    4
   2    6    6
   9    9    8
   2    3    8
   2    4    4
   8    6    1
   4    4    1
   1    3    4
   2    3    6
   3    9    2
   3    8    5
   9    9    4
   6    3    6
   2    6    8
   8    4    0

Matrix I:
 3.0  0.0
 0.0  3.0

Matrix A_I:
   3    4    8
   0    1    4
   7    8    1
   2    3    5
   7    9    6
   6    1    5
   8    7    0
   0    5    4
   3    3    8
   3    9    4
   6    5    5
   4    0    4
   7    0    1

In [15]:

for row in A_I:
    print(" ".join(str(elem).rjust(4) for elem in row))

   3    4    8
   0    1    4
   7    8    1
   2    3    5
   7    9    6
   6    1    5
   8    7    0
   0    5    4
   3    3    8
   3    9    4
   6    5    5
   4    0    4
   7    0    1
   0    5    2
   0    0    9
   6    4    0
   1    7    6
   6    3    0
   5    4    9
   9    9    6
   1    1    1
   5    3    3
   3    3    3
   6    3    4
   3    3    5
   1    8    9
   3    3    7
   5    2    9
   4    2    3
   5    3    1
   8    9    2
   9    6    6
   7    9    6
   8    5    9
   3    5    0
   1    6    4
   2    6    6
   9    9    8
   2    3    8
   2    4    4
   8    6    1
   4    4    1
   1    3    4
   2    3    6
   3    9    2
   3    8    5
   9    9    4
   6    3    6
   2    6    8
   8    4    0
   3    0    0
   0    3    0


In [16]:
mat=[]
for row in A:
    print(" ".join(str(elem).rjust(4) for elem in row))
    # print row times its transpose
    print("\nRow times its transpose:")
    print(np.outer(row, row))
    mat.append(np.array(np.outer(row, row).flatten()))

#  convert mat into a proper matrix
mat = np.array(mat)

   3    4    8

Row times its transpose:
[[ 9 12 24]
 [12 16 32]
 [24 32 64]]
   0    1    4

Row times its transpose:
[[ 0  0  0]
 [ 0  1  4]
 [ 0  4 16]]
   7    8    1

Row times its transpose:
[[49 56  7]
 [56 64  8]
 [ 7  8  1]]
   2    3    5

Row times its transpose:
[[ 4  6 10]
 [ 6  9 15]
 [10 15 25]]
   7    9    6

Row times its transpose:
[[49 63 42]
 [63 81 54]
 [42 54 36]]
   6    1    5

Row times its transpose:
[[36  6 30]
 [ 6  1  5]
 [30  5 25]]
   8    7    0

Row times its transpose:
[[64 56  0]
 [56 49  0]
 [ 0  0  0]]
   0    5    4

Row times its transpose:
[[ 0  0  0]
 [ 0 25 20]
 [ 0 20 16]]
   3    3    8

Row times its transpose:
[[ 9  9 24]
 [ 9  9 24]
 [24 24 64]]
   3    9    4

Row times its transpose:
[[ 9 27 12]
 [27 81 36]
 [12 36 16]]
   6    5    5

Row times its transpose:
[[36 30 30]
 [30 25 25]
 [30 25 25]]
   4    0    4

Row times its transpose:
[[16  0 16]
 [ 0  0  0]
 [16  0 16]]
   7    0    1

Row times its transpose:
[[49  0  7]
 [ 0  0  0]

In [17]:


print(mat)

A=mat

[[ 9 12 24 12 16 32 24 32 64]
 [ 0  0  0  0  1  4  0  4 16]
 [49 56  7 56 64  8  7  8  1]
 [ 4  6 10  6  9 15 10 15 25]
 [49 63 42 63 81 54 42 54 36]
 [36  6 30  6  1  5 30  5 25]
 [64 56  0 56 49  0  0  0  0]
 [ 0  0  0  0 25 20  0 20 16]
 [ 9  9 24  9  9 24 24 24 64]
 [ 9 27 12 27 81 36 12 36 16]
 [36 30 30 30 25 25 30 25 25]
 [16  0 16  0  0  0 16  0 16]
 [49  0  7  0  0  0  7  0  1]
 [ 0  0  0  0 25 10  0 10  4]
 [ 0  0  0  0  0  0  0  0 81]
 [36 24  0 24 16  0  0  0  0]
 [ 1  7  6  7 49 42  6 42 36]
 [36 18  0 18  9  0  0  0  0]
 [25 20 45 20 16 36 45 36 81]
 [81 81 54 81 81 54 54 54 36]
 [ 1  1  1  1  1  1  1  1  1]
 [25 15 15 15  9  9 15  9  9]
 [ 9  9  9  9  9  9  9  9  9]
 [36 18 24 18  9 12 24 12 16]
 [ 9  9 15  9  9 15 15 15 25]
 [ 1  8  9  8 64 72  9 72 81]
 [ 9  9 21  9  9 21 21 21 49]
 [25 10 45 10  4 18 45 18 81]
 [16  8 12  8  4  6 12  6  9]
 [25 15  5 15  9  3  5  3  1]
 [64 72 16 72 81 18 16 18  4]
 [81 54 54 54 36 36 54 36 36]
 [49 63 42 63 81 54 42 54 36]
 [64 40 72

In [18]:
import numpy as np



def caratheodory(P, w):
    n, d = P.shape
    if n <= d + 1:
        return P, w
    
    # Compute the matrix M (each column is pi - p1)
    M = (P[1:] - P[0]).T  # shape (d, n-1)

    # Perform SVD on M
    U, S, Vt = np.linalg.svd(M, full_matrices=False)
    
    # The smallest singular value is the last one in S, and its corresponding vector is the last row of Vt
    v = Vt[-1]

    # Include v1, which is the negative sum of the other entries in v
    v1 = -np.sum(v)
    v = np.insert(v, 0, v1)
    
    # Calculate alpha
    alpha = np.inf
    for i in range(n):
        if v[i] > 0:
            alpha = min(alpha, w[i] / v[i])
    
    # Calculate new weights u
    u = w - alpha * v
    u = np.maximum(u, 0)  # Ensure u is non-negative
    
    # Filter points with positive weights
    S = P[u > 0]
    u = u[u > 0]
    
    if len(S) > d + 1:
        return caratheodory(S, u)  # Recursive call if needed
    return S, u
print(A)
w=np.ones(len(A))   
w=[x/sum(w) for x in w]

d=len(A[0])
A= [tuple(row) for row in A]
# convert A inot a numpy array
A = np.array(A)

S, u = caratheodory(A, w)
# u=[u[p] for p in S]
print("Weighted subset (S, u):", S, u)



[[ 9 12 24 12 16 32 24 32 64]
 [ 0  0  0  0  1  4  0  4 16]
 [49 56  7 56 64  8  7  8  1]
 [ 4  6 10  6  9 15 10 15 25]
 [49 63 42 63 81 54 42 54 36]
 [36  6 30  6  1  5 30  5 25]
 [64 56  0 56 49  0  0  0  0]
 [ 0  0  0  0 25 20  0 20 16]
 [ 9  9 24  9  9 24 24 24 64]
 [ 9 27 12 27 81 36 12 36 16]
 [36 30 30 30 25 25 30 25 25]
 [16  0 16  0  0  0 16  0 16]
 [49  0  7  0  0  0  7  0  1]
 [ 0  0  0  0 25 10  0 10  4]
 [ 0  0  0  0  0  0  0  0 81]
 [36 24  0 24 16  0  0  0  0]
 [ 1  7  6  7 49 42  6 42 36]
 [36 18  0 18  9  0  0  0  0]
 [25 20 45 20 16 36 45 36 81]
 [81 81 54 81 81 54 54 54 36]
 [ 1  1  1  1  1  1  1  1  1]
 [25 15 15 15  9  9 15  9  9]
 [ 9  9  9  9  9  9  9  9  9]
 [36 18 24 18  9 12 24 12 16]
 [ 9  9 15  9  9 15 15 15 25]
 [ 1  8  9  8 64 72  9 72 81]
 [ 9  9 21  9  9 21 21 21 49]
 [25 10 45 10  4 18 45 18 81]
 [16  8 12  8  4  6 12  6  9]
 [25 15  5 15  9  3  5  3  1]
 [64 72 16 72 81 18 16 18  4]
 [81 54 54 54 36 36 54 36 36]
 [49 63 42 63 81 54 42 54 36]
 [64 40 72

In [19]:
# print(S)
for row in S:
    print(" ".join(str(elem).rjust(4) for elem in row))
    

  36    6   30    6    1    5   30    5   25
  64   56    0   56   49    0    0    0    0
   9    9   24    9    9   24   24   24   64
  36   24    0   24   16    0    0    0    0
   1    7    6    7   49   42    6   42   36
   9    9    9    9    9    9    9    9    9
  49   63   42   63   81   54   42   54   36
   1    6    4    6   36   24    4   24   16
   4   12   12   12   36   36   12   36   36
   4    8    8    8   16   16    8   16   16


In [20]:
for row in A:
    print(" ".join(str(elem).rjust(4) for elem in row))

   9   12   24   12   16   32   24   32   64
   0    0    0    0    1    4    0    4   16
  49   56    7   56   64    8    7    8    1
   4    6   10    6    9   15   10   15   25
  49   63   42   63   81   54   42   54   36
  36    6   30    6    1    5   30    5   25
  64   56    0   56   49    0    0    0    0
   0    0    0    0   25   20    0   20   16
   9    9   24    9    9   24   24   24   64
   9   27   12   27   81   36   12   36   16
  36   30   30   30   25   25   30   25   25
  16    0   16    0    0    0   16    0   16
  49    0    7    0    0    0    7    0    1
   0    0    0    0   25   10    0   10    4
   0    0    0    0    0    0    0    0   81
  36   24    0   24   16    0    0    0    0
   1    7    6    7   49   42    6   42   36
  36   18    0   18    9    0    0    0    0
  25   20   45   20   16   36   45   36   81
  81   81   54   81   81   54   54   54   36
   1    1    1    1    1    1    1    1    1
  25   15   15   15    9    9   15    9    9
   9    9 

In [21]:
print(len(S) )
u=[u[p] for p in S]
print(len(u) )
print(u)



10


IndexError: index 36 is out of bounds for axis 0 with size 10

In [ ]:
B=[[8,10, 7, 10, 12, 14, 13, 14, 11],[-1, 20, -5,-2, -4, -10, -5, -10, -25],[-1, -2, -5,-2, 18, -10, -5, -10, -25]]
B=np.array(B)
# print the SVD of B
U, s, VT = np.linalg.svd(B.T)
print("\nMatrix U:")
for row in U:
    print(" ".join(str(elem).rjust(4) for elem in row))
print("\nMatrix S:")
print(s)
print("\nMatrix VT:")
for row in VT:
    print(" ".join(str(elem).rjust(4) for elem in row))



Matrix U:
-0.10444954235010445 0.23161050744324602 -0.01282494831414034 -0.29799083847543106 -0.5493319612952462 -0.40120178354816866 -0.38205962657891546 -0.4012017835481686 -0.2771695196510972
0.13483783723279338 0.5383155375510381 -0.7151519594662439 -0.1164066337528785 0.2054160317140677 -0.015973749050336786 -0.10233011114417769 -0.015973749050336772 0.33743857385019516
-0.19469134439389807 0.0974049339647861 -0.014729756760896105 -0.009451487595586103 0.7206597432091264 -0.19679749924984313 -0.07347540607960282 -0.19679749924984313 -0.5916871223058828
-0.14934338154445892 0.2703759961135023 -0.016668990299225094 0.925606669569546 -0.14968579730767256 -0.08863645635603758 -0.09153992747739088 -0.08863645635603756 -0.03270434369260559
0.04746226147513229 0.5770418126817719 0.6958284742661008 -0.1164066337528785 0.2054160317140678 -0.015973749050336786 -0.10233011114417769 -0.015973749050336758 0.3374385738501951
-0.3893826887877962 0.19480986792957214 -0.029459513521792356 -0.0918

In [ ]:
#  calculatwe y the right singular vector that corresponds to
# the smallest singular value in the SVD
y=VT[-1]
print("\nVector y:")

print(y)


Vector y:
[-0.03287535 -0.69732391  0.7160018 ]


In [ ]:
-sum(y)

0.014197447519234352